# Generated by Django 2.2 on 2022-01-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1500, verbose_name='Заголовок')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual', models.BooleanField(verbose_name='Актуальность')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=1500, verbose_name='Имя пользователя')),
                ('text', models.TextField(default='', max_length=1000, verbose_name='Текст комемнтария')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_news.News', verbose_name='Новость')),
            ],
        ),
    ]
