# Generated by Django 2.2 on 2022-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20220127_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('a', 'actual'), ('n', 'no_actual')], default='a', max_length=1),
        ),
    ]
