# Generated by Django 2.2 on 2022-02-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_auto_20220221_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=1500, verbose_name='Имя пользователя'),
        ),
    ]
