# Generated by Django 2.2 on 2022-03-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_profile_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verify',
        ),
    ]
