# Generated by Django 2.2 on 2022-03-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0015_remove_profile_verify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'permissions': (('can_publish', 'может опубликовать'),)},
        ),
    ]
