# Generated by Django 2.2 on 2022-04-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20220401_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
