# Generated by Django 2.2 on 2022-04-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='file',
        ),
        migrations.AddField(
            model_name='picture',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
