# Generated by Django 2.2 on 2022-04-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_auto_20220411_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileUpd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
