# Generated by Django 2.2 on 2022-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0012_picture_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
