# Generated by Django 2.2 on 2022-02-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_news_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='status',
        ),
        migrations.AlterField(
            model_name='news',
            name='actual',
            field=models.BooleanField(choices=[(True, 'actual'), (False, 'no_actual')], default=True, verbose_name='Актуальность'),
        ),
    ]
