# Generated by Django 2.2 on 2022-01-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_auto_20220110_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={'ordering': ['title']},
        ),
    ]
