# Generated by Django 2.2 on 2022-01-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('email', models.CharField(max_length=50, verbose_name='Эл. почта')),
                ('telephone', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.Author', verbose_name='Автор объявления'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='heading',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.AdvertisementHeading', verbose_name='Наименование'),
        ),
    ]
