

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.7


stages:
  - build
  - test


before-script:
    - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy app/

black:
  stage: test
  script:
    - black --diff --check app/

isort:
  stage: test
  script:
    - isort --check-only app/

flask8:
  stage: test
  script:
    - flake8 app/