# Generated by Django 2.2 on 2022-02-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20220125_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='administration',
            field=models.CharField(choices=[('d', 'Удалено администратором')], default='', max_length=30, verbose_name='Администрирование'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_news.News', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='actual',
            field=models.BooleanField(choices=[(True, 'Активно'), (False, 'Неактивно')], default=True, verbose_name='Актуальность'),
        ),
    ]
