# Generated by Django 2.2 on 2022-02-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20220203_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='actual',
            field=models.BooleanField(choices=[(True, 'Активно'), (False, 'Неактивно')], default=True, verbose_name='Актуальность'),
        ),
    ]
