

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.7


stages:
  - build
  - test


before_script:
    - pip install -r requirements.txt
    - python.exe -m pip install --upgrade pip

unittest:
  stage: test
  script:
    - pytest hw1/tests

mypy:
  stage: test
  script:
    - mypy hw1/app/

black:
  stage: test
  script:
    - black --diff --check hw1/app/

isort:
  stage: test
  script:
    - isort --check-only --profile black --line-length 79 hw1/app/

flake8:
  stage: test
  script:
    - flake8 hw1/app/